name: lofi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  # 核心：像 Electron 的隐藏窗口一样加载 B站 网页
  flutter_inappwebview: ^6.0.0 
  # 存储：保存你的专注时长
  shared_preferences: ^2.2.2
  # 状态管理：让 UI 和逻辑解耦
  provider: ^6.1.1
  audio_service: ^0.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
